## BUILDER ##
FROM node:24-slim AS builder
WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .
RUN npx vite build

## RUNNER ##
FROM nginx:alpine AS runner

RUN apk add --no-cache bash

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
